/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const App: typeof import('antd').App
  const Button: typeof import('antd').Button
  const Input: typeof import('antd').Input
  const message: typeof import('antd').message
}
